//! Self-signed certificate helper for the swarm controller.
//!
//! A real deployment would use an internal CA; for the demo, the controller
//! generates an Ed25519 self-signed cert at first run and persists it under
//! the configured state directory. Workers pin the cert's SHA3-256
//! fingerprint instead of doing a hostname-based PKI dance, which keeps the
//! authentication surface small enough to fit on an IoT-class node.

use std::path::Path;

use anyhow::{Context, Result};
use rcgen::{CertificateParams, KeyPair, SanType};
use sha3::{Digest, Sha3_256};

/// On-disk cert + key (PEM) generated by [`load_or_generate`].
pub struct ServerIdentity {
    pub cert_pem: String,
    pub key_pem:  String,
}

impl ServerIdentity {
    /// 32-byte SHA3-256 fingerprint of the DER-encoded certificate.
    pub fn fingerprint_sha3_256(&self) -> Result<[u8; 32]> {
        let der = pem_certs_to_der(&self.cert_pem)?
            .into_iter()
            .next()
            .context("no certificate found in PEM")?;
        let mut h = Sha3_256::new();
        Digest::update(&mut h, &der);
        Ok(Digest::finalize(h).into())
    }
}

/// Load a self-signed cert from `dir` if both `cert.pem` and `key.pem` exist;
/// otherwise generate a fresh Ed25519 cert valid for `subject_hosts` and
/// persist the result.
pub fn load_or_generate(dir: &Path, subject_hosts: &[&str]) -> Result<ServerIdentity> {
    let cert_path = dir.join("cert.pem");
    let key_path  = dir.join("key.pem");

    if cert_path.exists() && key_path.exists() {
        let cert_pem = std::fs::read_to_string(&cert_path)
            .with_context(|| format!("read {}", cert_path.display()))?;
        let key_pem  = std::fs::read_to_string(&key_path)
            .with_context(|| format!("read {}", key_path.display()))?;
        return Ok(ServerIdentity { cert_pem, key_pem });
    }

    std::fs::create_dir_all(dir)
        .with_context(|| format!("create_dir_all {}", dir.display()))?;

    // Build a self-signed Ed25519 cert.
    // rcgen 0.13 API: build CertificateParams, then serialize_self_signed(&kp).
    let mut params = CertificateParams::new(
        subject_hosts.iter().map(|s| s.to_string()).collect::<Vec<_>>(),
    )?;
    for host in subject_hosts {
        if host.parse::<std::net::IpAddr>().is_ok() {
            params.subject_alt_names.push(SanType::IpAddress(host.parse()?));
        } else {
            params.subject_alt_names.push(SanType::DnsName(host.to_string().try_into()?));
        }
    }
    params.distinguished_name.push(rcgen::DnType::CommonName, "stir-swarm-ctrl");

    let key_pair = KeyPair::generate_for(&rcgen::PKCS_ED25519)?;
    let cert     = params.self_signed(&key_pair)?;

    let cert_pem = cert.pem();
    let key_pem  = key_pair.serialize_pem();

    std::fs::write(&cert_path, &cert_pem)
        .with_context(|| format!("write {}", cert_path.display()))?;
    std::fs::write(&key_path, &key_pem)
        .with_context(|| format!("write {}", key_path.display()))?;

    Ok(ServerIdentity { cert_pem, key_pem })
}

/// Parse all CERTIFICATE blocks out of a PEM string.
pub fn pem_certs_to_der(pem: &str) -> Result<Vec<Vec<u8>>> {
    let mut cur = pem.as_bytes();
    let mut out = Vec::new();
    while let Some(item) = rustls_pemfile::read_one_from_slice(cur)
        .map_err(|e| anyhow::anyhow!("pem parse: {e:?}"))?
    {
        match item.0 {
            rustls_pemfile::Item::X509Certificate(der) => {
                out.push(der.as_ref().to_vec());
            }
            _ => {}
        }
        cur = item.1;
    }
    Ok(out)
}

/// Parse the first PRIVATE KEY (PKCS#8) block out of a PEM string.
pub fn pem_first_private_key_der(pem: &str) -> Result<Vec<u8>> {
    let mut cur = pem.as_bytes();
    while let Some(item) = rustls_pemfile::read_one_from_slice(cur)
        .map_err(|e| anyhow::anyhow!("pem parse: {e:?}"))?
    {
        if let rustls_pemfile::Item::Pkcs8Key(key) = item.0 {
            return Ok(key.secret_pkcs8_der().to_vec());
        }
        cur = item.1;
    }
    anyhow::bail!("no PKCS#8 PRIVATE KEY found in PEM");
}
