// p256_scalar.rs — F_n arithmetic for NIST P-256, where n is the order
// of the elliptic-curve subgroup generated by the standard generator G.
//
// This is the native (out-of-circuit) reference for the *scalar field*
// of P-256 ECDSA.  The base-field counterpart lives in `p256_field.rs`.
//
// ─────────────────────────────────────────────────────────────────
// MODULUS & STRUCTURE
// ─────────────────────────────────────────────────────────────────
//
// n = ffffffff 00000000 ffffffff ffffffff bce6faad a7179e84 f3b9cac2 fc632551
//   = 2^256 − 2^224 + 2^192 + 2^96 − 1 − k    where k ≈ 2^128 (the curve
//                                              cofactor-times-Hasse-bound
//                                              correction; n ≠ p but is
//                                              close to p)
//
// Crucially, n is NOT a generalised-Mersenne (Solinas) prime — the low
// 192 bits are "random" hex.  This means we have no analog of the FIPS
// 186-4 §D.2.2 nine-sum fast reduction available for Fp.  Native
// arithmetic falls back to BigUint mod-n reduction; the in-circuit
// scalar mul gadget will use the *witness-quotient* approach already
// used by `p256_field_air::eval_mul_gadget`, parameterised by modulus.
//
// ─────────────────────────────────────────────────────────────────
// WHY F_n MATTERS FOR ECDSA-P256
// ─────────────────────────────────────────────────────────────────
//
// ECDSA verification computes:
//
//   1.  e  = SHA-256(message)             (truncated, then reduced mod n)
//   2.  w  = s^{-1}  mod n                 (Fermat: s^{n-2})
//   3.  u_1 = e · w   mod n
//   4.  u_2 = r · w   mod n
//   5.  R  = u_1 · G + u_2 · Q             (curve-group; Phase 3-4)
//   6.  x(R) mod n  ?=  r                  (Fp → Fn reduction)
//
// Steps 1–4 and 6 are pure Fn operations; this module supplies them
// natively.  The corresponding in-circuit AIR is `p256_scalar_air.rs`
// (Phase 2 v1) and reuses the witness-q mul layout with N_LIMBS_TIGHT
// substituted for P_LIMBS_TIGHT.
//
// ─────────────────────────────────────────────────────────────────
// LIMB REPRESENTATION (uniform 10×26, identical to F_p)
// ─────────────────────────────────────────────────────────────────
//
// We keep the same 10×26-bit-uniform layout as `p256_field` for
// downstream gadget composition: the scalar AIR can share trace-cell
// row layouts with the base-field AIR, simplifying the top-level
// verifier.  Total: 260 bits per element.

#![allow(non_snake_case, non_upper_case_globals, dead_code)]

use num_bigint::BigUint;
use num_traits::{Num, Zero};
use once_cell::sync::Lazy;

use crate::p256_field::{LIMB_BITS, LIMB_OFFSETS, NUM_LIMBS};

// ═══════════════════════════════════════════════════════════════════
//  Modulus n (the P-256 group order, FIPS 186-4 D.1.2.3)
// ═══════════════════════════════════════════════════════════════════

/// n in big-endian hex.  Used to derive the BigUint modulus.
const N_HEX: &str =
    "ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551";

/// Tight-form limbs of n itself (uniform 10×26).
///
/// Derivation: n in 32-bit u32 LE words is
///   word 0 = 0xfc632551
///   word 1 = 0xf3b9cac2
///   word 2 = 0xa7179e84
///   word 3 = 0xbce6faad
///   word 4 = 0xffffffff
///   word 5 = 0xffffffff
///   word 6 = 0x00000000
///   word 7 = 0xffffffff
///
/// Bits set, indexed by global bit position: a complex pattern (n is
/// not a Solinas prime).  We compute the limbs by extracting 26-bit
/// slices from the BigUint at runtime — the result is cached in a
/// `Lazy` static rather than hard-coded, keeping the constants
/// readable and verifiable against `N_HEX`.
pub static N_LIMBS_TIGHT: Lazy<[i64; NUM_LIMBS]> = Lazy::new(|| {
    let n = BigUint::from_str_radix(N_HEX, 16).unwrap();
    biguint_to_limbs(&n)
});

/// The BigUint representation of n, cached.
pub static N_BIGUINT: Lazy<BigUint> =
    Lazy::new(|| BigUint::from_str_radix(N_HEX, 16).unwrap());

// ═══════════════════════════════════════════════════════════════════
//  ScalarElement — 10-limb representation in i64 storage.
// ═══════════════════════════════════════════════════════════════════

/// Element of F_n, stored as 10 uniform-26-bit limbs in i64.
///
/// Same invariants as `p256_field::FieldElement`, but the modulus is
/// n (the P-256 group order) instead of p (the base-field prime).
#[derive(Clone, Copy, Debug)]
pub struct ScalarElement {
    pub limbs: [i64; NUM_LIMBS],
}

// ═══════════════════════════════════════════════════════════════════
//  BigUint ↔ limbs helpers
// ═══════════════════════════════════════════════════════════════════

fn biguint_to_limbs(x: &BigUint) -> [i64; NUM_LIMBS] {
    let bytes = x.to_bytes_be();
    let mut padded = [0u8; 32];
    if bytes.len() <= 32 {
        padded[32 - bytes.len()..].copy_from_slice(&bytes);
    } else {
        // Caller should have reduced mod n already; this branch
        // shouldn't fire for in-range inputs.
        padded.copy_from_slice(&bytes[bytes.len() - 32..]);
    }
    let mut limbs = [0i64; NUM_LIMBS];
    for i in 0..NUM_LIMBS {
        let mut v = 0u64;
        for b in 0..LIMB_BITS {
            let bit_pos = LIMB_OFFSETS[i] + b;
            if bit_pos >= 256 {
                break;
            }
            let byte_idx_be = 31 - (bit_pos / 8) as usize;
            let bit_in_byte = bit_pos % 8;
            let bit = (padded[byte_idx_be] >> bit_in_byte) & 1;
            v |= (bit as u64) << b;
        }
        limbs[i] = v as i64;
    }
    limbs
}

fn limbs_to_biguint(limbs: &[i64; NUM_LIMBS]) -> BigUint {
    let mut acc = BigUint::zero();
    for i in 0..NUM_LIMBS {
        let limb = BigUint::from(limbs[i] as u64);
        acc += limb << LIMB_OFFSETS[i];
    }
    acc
}

// ═══════════════════════════════════════════════════════════════════
//  Public API
// ═══════════════════════════════════════════════════════════════════

impl ScalarElement {
    /// The zero scalar.
    pub const fn zero() -> Self {
        Self {
            limbs: [0; NUM_LIMBS],
        }
    }

    /// The multiplicative identity.
    pub const fn one() -> Self {
        let mut l = [0i64; NUM_LIMBS];
        l[0] = 1;
        Self { limbs: l }
    }

    /// Decode from a 32-byte big-endian encoding (SEC1 / ANSI X9.62).
    /// Reduces modulo n in case the input integer is ≥ n.
    pub fn from_be_bytes(bytes: &[u8; 32]) -> Self {
        let raw = BigUint::from_bytes_be(bytes);
        let reduced = raw % &*N_BIGUINT;
        Self {
            limbs: biguint_to_limbs(&reduced),
        }
    }

    /// Decode from a 32-byte big-endian encoding *without* reducing.
    /// The caller must guarantee the input integer is < n; otherwise
    /// the resulting `ScalarElement` is non-canonical (the AIR will
    /// reject it via range-check + n-bound enforcement).
    pub fn from_be_bytes_unchecked(bytes: &[u8; 32]) -> Self {
        Self {
            limbs: biguint_to_limbs(&BigUint::from_bytes_be(bytes)),
        }
    }

    /// Encode to a canonical 32-byte big-endian representation.
    pub fn to_be_bytes(&self) -> [u8; 32] {
        let mut t = *self;
        t.freeze();
        let int = limbs_to_biguint(&t.limbs);
        let bytes = int.to_bytes_be();
        let mut padded = [0u8; 32];
        padded[32 - bytes.len()..].copy_from_slice(&bytes);
        padded
    }

    /// Loose addition (limb-wise).
    pub fn add(&self, other: &Self) -> Self {
        let mut r = [0i64; NUM_LIMBS];
        for i in 0..NUM_LIMBS {
            r[i] = self.limbs[i] + other.limbs[i];
        }
        Self { limbs: r }
    }

    /// Loose subtraction (limb-wise).  Result may have negative limbs.
    pub fn sub(&self, other: &Self) -> Self {
        let mut r = [0i64; NUM_LIMBS];
        for i in 0..NUM_LIMBS {
            r[i] = self.limbs[i] - other.limbs[i];
        }
        Self { limbs: r }
    }

    /// Negation: 0 − self (mod n), in loose form.
    pub fn neg(&self) -> Self {
        let mut r = [0i64; NUM_LIMBS];
        for i in 0..NUM_LIMBS {
            r[i] = -self.limbs[i];
        }
        Self { limbs: r }
    }

    /// Multiplication mod n.  Native: BigUint long multiply + mod.
    /// (The AIR will use the witness-q approach over 19 schoolbook
    /// positions, parameterised by N_LIMBS_TIGHT.)
    pub fn mul(&self, other: &Self) -> Self {
        let mut a_t = *self;
        a_t.freeze();
        let mut b_t = *other;
        b_t.freeze();
        let a_int = limbs_to_biguint(&a_t.limbs);
        let b_int = limbs_to_biguint(&b_t.limbs);
        let prod = (a_int * b_int) % &*N_BIGUINT;
        Self {
            limbs: biguint_to_limbs(&prod),
        }
    }

    /// Square — same as `self.mul(self)`.
    pub fn square(&self) -> Self {
        self.mul(self)
    }

    /// Multiply by a small i64 scalar.
    pub fn mul_small(&self, k: i64) -> Self {
        if k >= 0 {
            let mut bytes = [0u8; 32];
            bytes[24..32].copy_from_slice(&(k as u64).to_be_bytes());
            self.mul(&Self::from_be_bytes_unchecked(&bytes))
        } else {
            self.neg().mul_small(-k)
        }
    }

    /// Carry-chain reduction: bring each limb into [0, 2^26).  Native
    /// uses BigUint normalisation (the AIR will use Solinas-free
    /// per-limb chain identical to `p256_field::reduce` modulo the
    /// limb-9 wrap formula — which differs because n is not a Solinas
    /// prime; see Phase 2 v1 for the corresponding AIR design).
    pub fn reduce(&mut self) {
        let int = limbs_to_biguint(&self.limbs).clone();
        // Need to handle potentially-negative limbs.  Sum up positive
        // and negative parts separately.
        let mut pos = BigUint::zero();
        let mut neg = BigUint::zero();
        for i in 0..NUM_LIMBS {
            let mag = self.limbs[i].unsigned_abs();
            let term = BigUint::from(mag) << LIMB_OFFSETS[i];
            if self.limbs[i] >= 0 {
                pos += term;
            } else {
                neg += term;
            }
        }
        // pos − neg ≡ self (mod n).  Reduce.
        let n = &*N_BIGUINT;
        // Make sure (pos − neg) is non-negative by adding enough
        // multiples of n: take pos = pos + k·n for k large enough
        // that pos ≥ neg.
        let needed = if pos < neg {
            let diff = &neg - &pos;
            (&diff / n) + 1u32
        } else {
            BigUint::zero()
        };
        let pos = pos + &needed * n;
        let result = (pos - neg) % n;
        self.limbs = biguint_to_limbs(&result);
        // Suppress unused-variable lint on `int`.
        let _ = int;
    }

    /// Canonical-form normalisation: limbs in [0, 2^26) and integer
    /// in [0, n).  Required before byte encoding or comparison.
    pub fn freeze(&mut self) {
        // After reduce(), limbs are in [0, 2^26) and integer is in
        // [0, n).  reduce() does the heavy lifting via BigUint mod-n.
        self.reduce();
    }

    /// True iff this element equals zero (canonical-form comparison).
    pub fn is_zero(&self) -> bool {
        let mut t = *self;
        t.freeze();
        t.limbs.iter().all(|&l| l == 0)
    }

    /// True iff self == other after both are canonicalised.
    pub fn ct_eq(&self, other: &Self) -> bool {
        self.to_be_bytes() == other.to_be_bytes()
    }

    /// Inverse via Fermat's little theorem: self^{n−2} mod n.
    /// Square-and-multiply with the explicit binary expansion of n − 2.
    pub fn invert(&self) -> Self {
        let n_minus_2 = &*N_BIGUINT - 2u32;
        let mut acc = Self::one();
        // Walk MSB-first across all bits of n − 2.
        let bit_count = n_minus_2.bits();
        for i in (0..bit_count).rev() {
            acc = acc.square();
            if n_minus_2.bit(i) {
                acc = acc.mul(self);
            }
        }
        acc
    }
}

// ═══════════════════════════════════════════════════════════════════
//  Tests — cross-check against `num_bigint::BigUint` arithmetic mod n.
// ═══════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    fn pseudo_bytes(seed: u64, salt: u64) -> [u8; 32] {
        let mut b = [0u8; 32];
        for (i, byte) in b.iter_mut().enumerate() {
            *byte = (seed
                .wrapping_mul(0x9E37_79B9_7F4A_7C15)
                .wrapping_add(salt.wrapping_mul(i as u64 + 1).wrapping_mul(31))
                & 0xff) as u8;
        }
        b
    }

    fn pseudo_scalar(seed: u64) -> (BigUint, ScalarElement) {
        let raw = BigUint::from_bytes_be(&pseudo_bytes(seed, 0xa5a5_a5a5));
        let int = raw % &*N_BIGUINT;
        let scalar = ScalarElement::from_be_bytes_unchecked(
            &biguint_to_padded_be_bytes(&int),
        );
        (int, scalar)
    }

    fn biguint_to_padded_be_bytes(x: &BigUint) -> [u8; 32] {
        let bytes = x.to_bytes_be();
        let mut padded = [0u8; 32];
        padded[32 - bytes.len()..].copy_from_slice(&bytes);
        padded
    }

    fn scalar_to_biguint(s: &ScalarElement) -> BigUint {
        let mut t = *s;
        t.freeze();
        BigUint::from_bytes_be(&t.to_be_bytes())
    }

    #[test]
    fn n_constant_is_correct_size() {
        // n is exactly 256 bits.
        assert_eq!(N_BIGUINT.bits(), 256);
    }

    #[test]
    fn n_constant_decodes_to_zero() {
        // N_LIMBS_TIGHT represents n, which ≡ 0 (mod n).
        let n_scalar = ScalarElement {
            limbs: *N_LIMBS_TIGHT,
        };
        assert!(n_scalar.is_zero(), "n mod n ≠ 0");
    }

    #[test]
    fn zero_is_zero() {
        assert!(ScalarElement::zero().is_zero());
    }

    #[test]
    fn one_is_one() {
        let mut want = [0u8; 32];
        want[31] = 1;
        assert_eq!(ScalarElement::one().to_be_bytes(), want);
    }

    #[test]
    fn from_to_bytes_roundtrip() {
        for seed in 0u64..16 {
            let (int, s) = pseudo_scalar(seed);
            let bytes = s.to_be_bytes();
            assert_eq!(BigUint::from_bytes_be(&bytes), int, "seed {}", seed);
        }
    }

    #[test]
    fn add_matches_biguint() {
        for seed in 0u64..16 {
            let (a_int, a) = pseudo_scalar(seed);
            let (b_int, b) = pseudo_scalar(seed.wrapping_mul(7).wrapping_add(13));
            let r = a.add(&b);
            let expected = (&a_int + &b_int) % &*N_BIGUINT;
            assert_eq!(scalar_to_biguint(&r), expected, "add seed {}", seed);
        }
    }

    #[test]
    fn sub_matches_biguint() {
        for seed in 0u64..16 {
            let (a_int, a) = pseudo_scalar(seed);
            let (b_int, b) = pseudo_scalar(seed.wrapping_mul(7).wrapping_add(13));
            let r = a.sub(&b);
            let expected = (&a_int + &*N_BIGUINT - &b_int) % &*N_BIGUINT;
            assert_eq!(scalar_to_biguint(&r), expected, "sub seed {}", seed);
        }
    }

    #[test]
    fn mul_matches_biguint() {
        for seed in 0u64..16 {
            let (a_int, a) = pseudo_scalar(seed);
            let (b_int, b) = pseudo_scalar(seed.wrapping_mul(11).wrapping_add(7));
            let r = a.mul(&b);
            let expected = (&a_int * &b_int) % &*N_BIGUINT;
            assert_eq!(scalar_to_biguint(&r), expected, "mul seed {}", seed);
        }
    }

    #[test]
    fn invert_times_self_is_one() {
        for seed in 1u64..6 {
            let (a_int, a) = pseudo_scalar(seed);
            if a_int.is_zero() {
                continue;
            }
            let inv = a.invert();
            let prod = a.mul(&inv);
            assert_eq!(
                prod.to_be_bytes(),
                ScalarElement::one().to_be_bytes(),
                "a · a⁻¹ ≠ 1 (seed {})",
                seed
            );
        }
    }

    #[test]
    fn n_minus_1_squared_is_one() {
        // (n − 1)^2 ≡ 1 (mod n).
        let mut neg_one = ScalarElement::one().neg();
        neg_one.freeze();
        let sq = neg_one.square();
        assert_eq!(sq.to_be_bytes(), ScalarElement::one().to_be_bytes());
    }

    #[test]
    fn distributivity() {
        // (a + b) · c == a·c + b·c
        for seed in 0u64..4 {
            let (_, a) = pseudo_scalar(seed);
            let (_, b) = pseudo_scalar(seed + 100);
            let (_, c) = pseudo_scalar(seed + 200);
            let lhs = a.add(&b).mul(&c);
            let rhs = a.mul(&c).add(&b.mul(&c));
            assert_eq!(
                lhs.to_be_bytes(),
                rhs.to_be_bytes(),
                "distributivity seed {}",
                seed
            );
        }
    }
}
